services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        # user: root
        networks:
            # - docker_myNet
            - docker_myNet1
        volumes:
            - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
            - prom_vol:/prometheus
            - ./conf/rules.yml:/etc/prometheus/rules.yml
        ports:
            - 9090:9090
        depends_on:
            - node-exporter
            - alert-manager

# ****************************************************

    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        # ports:
        #     - 9100:9100
        #pid: host
        # user: root
        # userns_mode: "host"
        networks:
            # - docker_myNet
            - docker_myNet1
        volumes:
            - /:/host
        command:
            - --path.rootfs=/host
    
# *********************************************************

    postgres-exporter:
        image: prometheuscommunity/postgres-exporter:v0.16.0
        container_name: postgres-exporter
        networks:
            # - docker_myNet
            - docker_myNet1

# **********************************************************

    alert-manager:
        build:
            context: .
            dockerfile: alertmanagerDockerfile
        container_name: alert-manager
        env_file:
            - .env
        volumes:
            - ./conf/alertmanager.yml:/etc/alertmanager/alertmanager.yml
            - alert_vol:/alertmanager
        ports:
            - 9093:9093
        networks:
            # - docker_myNet
            - docker_myNet1

# ************************************************************

    grafana:
        image: grafana/grafana
        container_name: grafana
        env_file:
            - .env
        volumes:
            - grafana_vol:/var/lib/grafana
        networks:
            # - docker_myNet
            - docker_myNet1
        ports:
            - 3000:3000


networks:
    docker_myNet1:
    # docker_myNet:
        # external: true

volumes:
    prom_vol:
    alert_vol:
    grafana_vol:
