global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  # - job_names: 'postgres_exporter'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']