global:
  scrape_interval: 1s

# default retention time 15d
# storage.tsdb:
#   retention.time: 1m

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alert-manager:9093']

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
